services:
  mariadb:
    image: mariadb
    container_name: ${ENV}_Myfab_Db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - ${VOLUMES_PATH}/myfab-tickets/mariaDB/:/var/lib/mysql
    networks:
      - myfab-internal-network

  back:
    image: ghcr.io/devinci-fablab/myfab-tickets-backend:latest
    restart: unless-stopped
    container_name: prod_Myfab_Back
    depends_on:
      - 'mariadb'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      API: ${API}
      FRONT_URL: ${FRONT_URL}
      SPECIALTOKEN: ${SPECIALTOKEN}
      SHOWSWAGGER: ${SHOWSWAGGER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADSF_ENTRYPOINT: ${ADSF_ENTRYPOINT}
      ADSF_ISSUER: ${ADSF_ISSUER}
      ADFS_FRONT_URL: ${ADFS_FRONT_URL}
    volumes:
      - ${VOLUMES_PATH}/myfab-tickets/back/data/:/home/node/MyFab_Back/data/
      - ${VOLUMES_PATH}/myfab-tickets/back/logs/:/home/node/MyFab_Back/logs/
    networks:
      - myfab-internal-network
      - traefik-network
    expose:
      - 5000
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.routers.myfab.rule=Host(`${HOST}`) && PathPrefix(`/api/`)'
      - 'traefik.http.middlewares.myfabapi.stripprefix.prefixes=/api'
      - 'traefik.http.routers.myfab.entrypoints=websecure'
      - 'traefik.http.routers.myfab.tls.certresolver=myresolver'
      - 'traefik.http.services.myfab.loadbalancer.server.port=5000'
      - 'com.centurylinklabs.watchtower.enable=true'

  front:
    image: ghcr.io/devinci-fablab/myfab-tickets-frontend:latest
    restart: unless-stopped
    container_name: prod_Myfab_Front
    depends_on:
      - 'back'
      - 'mariadb'
    environment:
      API: ${API}
      BASE_PATH: ${BASE_PATH}
      IS_TEST_MODE: ${IS_TEST_MODE}
      DARK_MODE_IN_TEST_MODE: ${DARK_MODE_IN_TEST_MODE}
    networks:
      - myfab-internal-network
      - traefik-network
    expose:
      - 3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.routers.myfab.rule=Host(`${HOST}`)'
      - 'traefik.http.routers.myfab.entrypoints=websecure'
      - 'traefik.http.routers.myfab.tls.certresolver=myresolver'
      - 'traefik.http.services.myfab.loadbalancer.server.port=3000'
      - 'com.centurylinklabs.watchtower.enable=true'

networks:
  traefik-network:
    external: true
  myfab-internal-network:
    driver: bridge