services:
  mariadb:
    image: mariadb
    container_name: ${ENV}_Myfab_Db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - ${VOLUMES_PATH}/myfab-tickets/mariaDB/:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - traefik-network

  back:
    build:
      context: back
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ${ENV}_Myfab_Back
    depends_on:
      - 'mariadb'
    volumes:
      - ${VOLUMES_PATH}/myfab-tickets/back/data/:/home/node/MyFab_Back/data/
      - ${VOLUMES_PATH}/myfab-tickets/back/logs/:/home/node/MyFab_Back/logs/
      - ./.env:/home/node/MyFab_Back/.env
    expose:
      - '5000'
    networks:
      - traefik-network

  front:
    build:
      context: front
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ${ENV}_Myfab_Front
    depends_on:
      - 'back'
    volumes:
      - ./.env:/home/node/MyFab_Front/.env
    expose:
      - '3000'
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myfab.rule=Host(`${HOST}`)'
      - 'traefik.http.routers.myfab.entrypoints=websecure'
      - 'traefik.http.routers.myfab.tls.certresolver=myresolver'
      - 'traefik.http.services.myfab.loadbalancer.server.port=3000'

networks:
  traefik-network:
    external: true
