FROM node:16.19.0
WORKDIR /my-project
COPY ./front/package*.json ./
RUN npm i -g next
RUN npm install
COPY ./front/ .
COPY .env .env.local
RUN next build
ENV NODE_ENV=production

EXPOSE 3000
CMD ["npm", "run", "start"]
