version: "3"

services:
  mariadb:
    image: mariadb
    container_name: Myfab_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - mariaDb:/var/lib/mysql
    networks:
      - MyFab

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    restart: always
    container_name: Myfab_Back
    depends_on:
      - "mariadb"
    volumes:
      - ./back/data/:/home/node/MyFab/back/data/
      - ./back/logs/:/home/node/MyFab/back/logs/
      - ./.env:/home/node/MyFab/back/.env
    ports:
      - ${PORT_BACK}:5000
    networks:
      - MyFab

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: always
    container_name: Myfab_Front
    depends_on:
      - "back"
    volumes:
      - ./back/data/:/home/node/MyFab/back/data/
      - ./.env:/home/node/MyFab/front/.env
    ports:
      - ${PORT_FRONT}:3000
    networks:
      - MyFab

volumes:
  mariaDb:

networks:
  MyFab:
