FROM node:18.13.0

COPY ./back/package*.json /home/node/MyFabUltimate_Back/
WORKDIR /home/node/MyFabUltimate_Back/
RUN npm install
COPY ./back/ .
COPY .env .
RUN npm run prepareFolders
CMD ["npm", "run", "startOnServer"]
