name: Test Back-end
run-name: ${{ github.actor }} push "${{ github.event.head_commit.message }}" 🚀
on: [push]
jobs:
  Test-Back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd back/ && npm i
      - name: Run test
        run: |
          cd back/ && npm test
