name: Linter for MyFab
run-name: "Linter : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install linter
        run: |
          cd back/ && npm install --save-dev --save-exact prettier
      - name: Check code
        run: |
          cd back/ && if npx prettier -c . ; then echo "Linter back is ok :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY; else echo -e "Linter back failed :x:\n\`\`\`" >> $GITHUB_STEP_SUMMARY; npx prettier -c . 2>> $GITHUB_STEP_SUMMARY > /dev/null; echo -e "\`\`\`" >> $GITHUB_STEP_SUMMARY; fi
