name: Test build
run-name: "Build : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo PORT_FRONT=3000 > .env
          echo PORT_BACK=5000 >> .env
          echo API=http://localhost:5000 >> .env
          echo BASE_PATH=/test >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USER=test >> .env
          echo DB_ROOT_PASSWORD=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo DB_PASSWORD=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo DB_DATABASE=myFab >> .env
          echo SPECIALTOKEN=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo SHOWSWAGGER=false >> .env
          echo ACTIVELOGS=false >> .env
          echo ADSF_ENTRYPOINT=http://localhost:8080/simplesaml/saml2/idp/SSOService.php >> .env
          echo ADSF_ISSUER=http://app.example.com >> .env
          echo ADFS_FRONT_URL=http://localhost:3000/test/ >> .env
          ls -lA .env
      - name: Build back
        run: |
          docker-compose build back >> $GITHUB_STEP_SUMMARY

  Build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo PORT_FRONT=3000 > .env
          echo PORT_BACK=5000 >> .env
          echo API=http://localhost:5000 >> .env
          echo BASE_PATH=/test >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USER=test >> .env
          echo DB_ROOT_PASSWORD=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo DB_PASSWORD=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo DB_DATABASE=myFab >> .env
          echo SPECIALTOKEN=$(echo $RANDOM | md5sum | head -c 20; echo;) >> .env
          echo SHOWSWAGGER=false >> .env
          echo ACTIVELOGS=false >> .env
          echo ADSF_ENTRYPOINT=http://localhost:8080/simplesaml/saml2/idp/SSOService.php >> .env
          echo ADSF_ISSUER=http://app.example.com >> .env
          echo ADFS_FRONT_URL=http://localhost:3000/test/ >> .env
          ls -lA .env
      - name: Build front
        run: |
          docker-compose build front >> $GITHUB_STEP_SUMMARY
