name: Test Back-end
run-name: "Back : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd back/ && npm install
      - name: Create .env file
        run: |
          echo SPECIALTOKEN=$(echo $RANDOM | md5sum | head -c 20; echo;) >> back/.env
          ls -lA back/.env
      - name: Run test
        run: |
          cd back/ && export NODE_OPTIONS=--no-experimental-fetch && npm test >> $GITHUB_STEP_SUMMARY
