name: Test Front-end
run-name: "Front : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Test-end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd front/ && npm install
      - name: Run build
        run: |
          cd front/ && npm run build
